spring:
  application:
    name: "Tire Exchange Application"

# This app's url (parenthesis are omitted in the real url, just for clarification here):
# http://localhost:[server.port][server.servlet.context-path]
server:
  port: 8080
  servlet:
    context-path: "/tire-exchange"



tire-exchange-sites:
  - name: "Manchester"
    address: "14 Bury New Rd, Manchester"
    vehicleTypes:
      - "Car"
      - "Truck"
    apiBaseUrl: "http://localhost:9003/api/v1/"

  - name: "London"
    address: "1A Gunton Rd, London"
    vehicleTypes:
      - "Car"
    apiBaseUrl: "http://localhost:9004/api/v2/"
