spring:
  application:
    name: "Tire Exchange Application"

# This app's url (parenthesis are omitted in the real url, just for clarification here):
# http://localhost:[server.port][server.servlet.context-path]
server:
  port: 8080
  servlet:
    context-path: "/tire-exchange"


# Each site will have a unique siteId (a number, which is ascending).
# This ensures, that all the other information about sites can be changed if needed (won't break the code).
tire-exchange-sites:
  - siteId: "1"
    name: "Manchester"
    address: "14 Bury New Rd, Manchester"
    vehicleTypes:
      - "Car"
      - "Truck"
    apiBaseUrl: "http://localhost:9003/api/v1/"

  - siteId: "2"
    name: "London"
    address: "1A Gunton Rd, London"
    vehicleTypes:
      - "Car"
    apiBaseUrl: "http://localhost:9004/api/v2/"
